baseURL: "https://raphaelhuleux.github.io" 
title: Raphaël Huleux
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

menu:
    main:
        - name: CV
          url: cv.pdf
          weight: 1
        - name: Job-Market Paper
          url: jmp.pdf
          weight: 2  
        - name: Papers
          url: papers/
          weight: 3
        - name: Courses
          url: courses/
          weight: 4
        - name: Blog
          url: blog/
          weight: 5

params:
    #description: "I'm a 4th year PhD student in the Economics Department of the Copenhagen Business School. \\ 
    #I am interested in the impact of inequality on financial markets and the transmission of monetary policy, and in the macroeconomic consequences of climate change policies."
    author: Raphaël Huleux
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Raphaël Huleux
          subtitle: "I'm a 4th year PhD student in the Economics Department of the Copenhagen Business School, under the supervision of David Jinkins and Birthe Larsen.
          
          <br><br>
          I am interested in the impact of inequality on financial markets and the transmission of monetary policy, and in the macroeconomic consequences of climate change policies. something"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Raphaël Huleux
          buttons:
            - name: CV
              url: cv.pdf
            - name: Job-market paper
              url: jmp.pdf
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Blog
              url: blog/

    socialIcons:
        - name: Email
          url: mailto:raphael.huleux@gmail.com
        - name: GitHub
          url: https://github.com/raphaelhuleux
        - name: Twitter
          url: https://x.com/raphaelhuleux

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Raphaël Huleux"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2