baseURL: "https://raphaelhuleux.github.io/"
title: Raphaël Huleux
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv.pdf
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3

params:
    description: "This website hosts Raphaël Huleux's research papers, course materials, curriculum vitae, and contact information."
    author: Raphaël Huleux
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Raphaël Huleux
          subtitle: "I am a Post-Doctoral Researcher at the University of Copenhagen working with Prof. Jeppe Druedahl, interested in macroeconomics, inequality, and fiscal and monetary policy."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv.pdf
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Blog
              url: blog/
    socialIcons:
        - name: Email
          url: mailto:raphael.huleux@gmail.com
        - name: GitHub
          url: https://github.com/raphaelhuleux
        - name: LinkedIn
          url: https://www.linkedin.com/in/rapha%C3%ABl-huleux-761840b1/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Raphaël Huleux"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2